# ------------------------------------------------
# Typus Admin Configuration File
# ------------------------------------------------
#
# Post:
#   fields:
#     list: title, category_id, created_at, status
#     form: title, body, status, created_at
#     relationship: title, status
#   actions:
#     list: cleanup
#     form: send_as_newsletter
#   order_by: created_at
#   relationships: categories
#   filters: status, created_at, category_id
#   search: title body
#   module: Content
#   description: Some text to describe the model
#
# ------------------------------------------------

Typus User:
  fields:
    list: first_name, last_name, email, status, admin
    form: first_name, last_name, email, password, password_confirmation
  actions:
    list:
    form:
  filters: status
  search: first_name, last_name, email
  module: Typus
  description: System Users Administration


Page:
  fields:
    list: title, slug, status, position
    form: title, slug, body
  actions:
    list:
    form:
  order_by: position
  relationships:
  filters:
  search:
  module: Portfolio
  description:

Project:
  fields:
    list: title, status
    form: title, description, status
  actions:
    list:
    form:
  order_by:
  relationships: assets
  filters: status, created_at
  search:
  module: Portfolio
  description:

Asset:
  fields:
    list: filename
    form: uploaded_data, preview
  module: Portfolio
